package terraform_test

import (
	"bytes"
	"log/slog"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/c3xdev/c3x/internal/parser/terraform"
)

// .tf.json files are configuration, and used to be ignored entirely.
func TestTfJSONFileIsParsed(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	write(t, dir, "main.tf.json", `{
	  "//": "generated by a CDK",
	  "variable": {
	    "size": { "type": "number", "default": 100 },
	    "azs":  { "type": "list(string)", "default": ["a", "b", "c"] }
	  },
	  "provider": {
	    "aws": [
	      { "region": "us-east-1" },
	      { "alias": "eu", "region": "eu-west-1" }
	    ]
	  },
	  "locals": { "type": "m5.large", "name": "web-${var.size}" },
	  "resource": {
	    "aws_instance": {
	      "web": {
	        "count": "${length(var.azs)}",
	        "instance_type": "${local.type}",
	        "tags": { "Name": "${local.name}", "kubernetes.io/role": "node" },
	        "root_block_device": { "volume_size": "${var.size}" },
	        "ebs_block_device": [{ "volume_size": 10 }, { "volume_size": 20 }],
	        "depends_on": ["aws_s3_bucket.logs"],
	        "lifecycle": { "create_before_destroy": true }
	      },
	      "eu": {
	        "provider": "aws.eu",
	        "instance_type": "t3.micro",
	        "dynamic": {
	          "ebs_block_device": {
	            "for_each": [1, 2],
	            "iterator": "d",
	            "content": { "volume_size": "${d.value * 100}" }
	          }
	        }
	      }
	    }
	  },
	  "output": { "ip": { "value": "${aws_instance.web[0].public_ip}" } }
	}`)
	got, err := terraform.ParseDirectory(dir, terraform.Options{Offline: true})
	if err != nil {
		t.Fatal(err)
	}
	rs := byName(got)
	if len(got) != 4 {
		t.Fatalf("got %v; want web[0..2] and eu", names(got))
	}
	web := rs["web[2]"].Attributes
	if web["instance_type"] != "m5.large" {
		t.Errorf("instance_type = %v, want m5.large", web["instance_type"])
	}
	if want := map[string]any{"Name": "web-100", "kubernetes.io/role": "node"}; !reflect.DeepEqual(web["tags"], want) {
		t.Errorf("tags = %#v, want %#v", web["tags"], want)
	}
	// Nested blocks written as JSON objects have the shape literal blocks
	// have: a map for one, a list of maps for several.
	if want := map[string]any{"volume_size": float64(100)}; !reflect.DeepEqual(web["root_block_device"], want) {
		t.Errorf("root_block_device = %#v, want %#v", web["root_block_device"], want)
	}
	wantEBS := []any{map[string]any{"volume_size": float64(10)}, map[string]any{"volume_size": float64(20)}}
	if !reflect.DeepEqual(web["ebs_block_device"], wantEBS) {
		t.Errorf("ebs_block_device = %#v, want %#v", web["ebs_block_device"], wantEBS)
	}
	eu := rs["eu"]
	if regionOf(eu) != "eu-west-1" {
		t.Errorf("eu region = %q; provider = \"aws.eu\" must select the aliased provider", regionOf(eu))
	}
	wantDyn := []any{map[string]any{"volume_size": float64(100)}, map[string]any{"volume_size": float64(200)}}
	if !reflect.DeepEqual(eu.Attributes["ebs_block_device"], wantDyn) {
		t.Errorf("dynamic ebs_block_device = %#v, want %#v", eu.Attributes["ebs_block_device"], wantDyn)
	}
	if regionOf(rs["web[0]"]) != "us-east-1" {
		t.Errorf("web region = %q, want us-east-1", regionOf(rs["web[0]"]))
	}
}

// JSON and native files mix in one module, a .tofu.json shadows the
// .tf.json of the same name, JSON override files apply, and a JSON module
// is expanded.
func TestTfJSONMixedWithNativeAndModules(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	mustMkdir(t, filepath.Join(dir, "db"))
	write(t, filepath.Join(dir, "db"), "main.tf.json", `{
	  "variable": { "class": {} },
	  "resource": { "aws_db_instance": { "db": { "instance_class": "${var.class}" } } }
	}`)
	write(t, dir, "main.tf", `resource "aws_instance" "web" { instance_type = "t3.micro" }`)
	write(t, dir, "db.tf.json", `{ "module": { "db": { "source": "./db", "class": "db.t3.micro" } } }`)
	write(t, dir, "db.tofu.json", `{ "module": { "db": { "source": "./db", "class": "db.r6g.large" } } }`)
	write(t, dir, "web_override.tf.json", `{ "resource": { "aws_instance": { "web": { "instance_type": "m5.large" } } } }`)
	got, err := terraform.ParseDirectory(dir, terraform.Options{Offline: true})
	if err != nil {
		t.Fatal(err)
	}
	rs := byName(got)
	if len(got) != 2 {
		t.Fatalf("got %v; want web and module.db.db", names(got))
	}
	if it := rs["web"].Attributes["instance_type"]; it != "m5.large" {
		t.Errorf("web instance_type = %v; want the JSON override's m5.large", it)
	}
	if ic := rs["module.db.db"].Attributes["instance_class"]; ic != "db.r6g.large" {
		t.Errorf("module.db.db instance_class = %v; want db.r6g.large from db.tofu.json", ic)
	}
}

// ParseFile accepts a single .tf.json file.
func TestParseFileTfJSON(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	write(t, dir, "main.tf.json", `{"resource": {"aws_instance": {"web": {"instance_type": "t3.micro"}}}}`)
	got, err := terraform.ParseFile(filepath.Join(dir, "main.tf.json"), terraform.Options{Offline: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 || got[0].Attributes["instance_type"] != "t3.micro" {
		t.Fatalf("got %d resources; want aws_instance.web", len(got))
	}
}

// Malformed JSON fails like malformed HCL does; a construct the
// translation can't represent is skipped with a warning naming it,
// never silently.
func TestTfJSONErrorsAndWarnings(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	write(t, dir, "main.tf.json", `{"resource": {`)
	if _, err := terraform.ParseDirectory(dir, terraform.Options{Offline: true}); err == nil ||
		!strings.Contains(err.Error(), "main.tf.json") {
		t.Errorf("err = %v; want a parse error naming main.tf.json", err)
	}

	dir = t.TempDir()
	write(t, dir, "main.tf.json", `{
	  "resource": { "aws_instance": { "web": { "instance_type": "t3.micro", "bad key": 1 } } },
	  "mystery": {}
	}`)
	var logs bytes.Buffer
	logger := slog.New(slog.NewTextHandler(&logs, nil))
	got, err := terraform.ParseDirectory(dir, terraform.Options{Offline: true, Logger: logger})
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 {
		t.Fatalf("got %d resources; the rest of the file must still parse", len(got))
	}
	for _, key := range []string{"mystery", "bad key"} {
		if !strings.Contains(logs.String(), key) {
			t.Errorf("no warning names %q; logs:\n%s", key, logs.String())
		}
	}
}
